"""Expression calibration engine.

After a command executes successfully, the calibration engine compares
the actual output against the expected expression. If there's a mismatch
(e.g., command returns "scram-sha-256" but expression says "==md5"),
the engine can infer a corrected expression from the actual output.

This is especially useful for:
- Config values that differ between OS distributions
- Version-specific default values
- Expressions generated by the LLM that assumed a wrong default

Usage::

    from backend.core.calibration_engine import calibrate_expression

    new_expr = calibrate_expression(
        actual_output="scram-sha-256",
        current_expression="==md5",
        rule_title="Ensure password encryption is set correctly",
    )
    # Returns "==scram-sha-256" or None if no calibration needed
"""

from __future__ import annotations

import logging
import re
from typing import Any

logger = logging.getLogger(__name__)


def calibrate_expression(
    actual_output: str,
    current_expression: str,
    rule_title: str = "",
    status: str = "",
) -> str | None:
    """Suggest a calibrated expression based on actual command output.

    Returns a corrected expression string, or ``None`` if no calibration
    is warranted (i.e., the current expression is fine or the output is
    too ambiguous to calibrate from).

    Only calibrates on FAIL results where the output looks like a valid
    value (not an error message).
    """
    if not actual_output or not current_expression:
        return None

    output = actual_output.strip()
    expr = current_expression.strip()

    # Don't calibrate error outputs
    if _looks_like_error(output):
        return None

    # Don't calibrate compound expressions (too complex)
    if "&&" in expr:
        return None

    # --- Numeric comparisons ---
    m = re.match(r'^(>=|<=|==|!=|>|<)\s*(-?\d+(?:\.\d+)?)$', expr)
    if m:
        op, expected_val = m.group(1), m.group(2)
        return _calibrate_numeric(output, op, expected_val, rule_title)

    # --- String equality ---
    m = re.match(r'^==(.*)', expr)
    if m:
        expected = m.group(1)
        return _calibrate_string_eq(output, expected, rule_title)

    # --- String inequality ---
    m = re.match(r'^!=(.*)', expr)
    if m:
        expected = m.group(1)
        return _calibrate_string_neq(output, expected, rule_title)

    # --- Contains ---
    m = re.match(r'^contains:(.*)', expr)
    if m:
        expected = m.group(1)
        return _calibrate_contains(output, expected, rule_title)

    # --- not_empty ---
    if expr == "not_empty":
        # If output is empty but command succeeded, this might be expected
        if not output:
            return None  # Can't calibrate — output is genuinely empty
        return None  # not_empty should pass with any output

    return None


def _looks_like_error(output: str) -> bool:
    """Check if output looks like an error message rather than a value."""
    error_patterns = [
        "error:", "ERROR:", "ERROR ", "fatal:", "FATAL:",
        "permission denied", "command not found",
        "no such file", "connection refused",
        "traceback", "exception", "stack trace",
    ]
    output_lower = output.lower()
    return any(p.lower() in output_lower for p in error_patterns)


def _calibrate_numeric(
    output: str, op: str, expected_val: str, title: str,
) -> str | None:
    """Calibrate numeric comparison expressions."""
    # Extract first number from output
    m = re.search(r'(-?\d+(?:\.\d+)?)', output)
    if not m:
        return None

    actual = m.group(1)

    # If it's an == and the value is close but not equal, recalibrate
    if op == "==" and actual != expected_val:
        # For on/off style checks, don't recalibrate (0/1 are intentional)
        if expected_val in ("0", "1") and actual in ("0", "1"):
            return None  # This is a genuine PASS/FAIL, not miscalibration
        # For larger ranges, suggest the actual value
        return f"=={actual}"

    return None


def _calibrate_string_eq(
    output: str, expected: str, title: str,
) -> str | None:
    """Calibrate string equality expressions."""
    # Normalize for comparison
    output_norm = output.strip().lower()
    expected_norm = expected.strip().lower()

    if output_norm == expected_norm:
        return None  # Already matches

    # Common false-FAIL patterns:
    # "on"/"off" vs "ON"/"OFF" → case mismatch, fix expression casing
    if output_norm in ("on", "off", "true", "false", "yes", "no"):
        return f"=={output.strip()}"

    # Password encryption: "scram-sha-256" vs "md5"
    # This is a genuine security-relevant difference — don't calibrate
    tl = title.lower()
    if "encrypt" in tl or "password" in tl or "hash" in tl:
        return None

    # For other strings, if output is a single clean value, suggest it
    if len(output.split()) <= 3 and len(output) < 100:
        return f"=={output.strip()}"

    return None


def _calibrate_string_neq(
    output: str, expected: str, title: str,
) -> str | None:
    """Calibrate string inequality expressions."""
    output_norm = output.strip().lower()
    expected_norm = expected.strip().lower()

    # If output equals the "bad" value, this is a real FAIL
    if output_norm == expected_norm:
        return None

    return None  # != expressions are usually correct if they pass


def _calibrate_contains(
    output: str, expected: str, title: str,
) -> str | None:
    """Calibrate contains: expressions."""
    if not expected:
        return None

    # If output doesn't contain the expected string, check for
    # common alternatives
    if expected.lower() not in output.lower():
        # pgaudit vs pg_stat_statements confusion
        if expected.lower() == "pgaudit" and "pg_stat_statements" in output.lower():
            return None  # Different extension, don't calibrate

    return None  # contains: is usually correct


# ═══════════════════════════════════════════════════════════════════
# Batch Calibration (post-scan)
# ═══════════════════════════════════════════════════════════════════

def calibrate_scan_results(
    findings: list[Any],
    db: Any = None,
    auto_apply: bool = False,
) -> list[dict[str, Any]]:
    """Review FAIL findings from a scan and suggest expression calibrations.

    Returns a list of calibration suggestions. If *auto_apply* is True
    and the suggestion has high confidence, updates the RuleCommand.
    """
    suggestions: list[dict[str, Any]] = []

    for finding in findings:
        if finding.status != "FAIL":
            continue

        output = finding.actual_output or ""
        expr = finding.expected_output or ""
        rule = finding.rule if hasattr(finding, "rule") else None
        title = rule.title if rule else ""

        calibrated = calibrate_expression(output, expr, title, finding.status)
        if calibrated:
            suggestions.append({
                "finding_id": finding.id,
                "rule_id": finding.rule_id,
                "current_expression": expr,
                "suggested_expression": calibrated,
                "actual_output": output[:200],
                "rule_title": title,
            })

            if auto_apply and db:
                _apply_calibration(finding, calibrated, db)

    logger.info("Calibration: %d suggestions from %d findings",
                len(suggestions), len(findings))
    return suggestions


def _apply_calibration(finding: Any, new_expr: str, db: Any) -> None:
    """Apply a calibration to the RuleCommand behind a finding."""
    try:
        from backend.models.rule_command import RuleCommand
        from datetime import datetime, timezone

        cmd = db.query(RuleCommand).filter(
            RuleCommand.rule_id == finding.rule_id
        ).first()
        if cmd and not cmd.is_protected:
            cmd.expected_output_regex = new_expr
            cmd.confidence_score = 0.70
            cmd.confidence_source = "calibrated"
            cmd.updated_at = datetime.now(timezone.utc)
            db.commit()
    except Exception as exc:
        logger.warning("Failed to apply calibration: %s", exc)
        try:
            db.rollback()
        except Exception:
            pass
