<#
.SYNOPSIS
    Installs and configures OpenSSH Server on Windows for AuditForge.

.DESCRIPTION
    Run this script AS ADMINISTRATOR on a Windows target when WinRM is
    not available or not preferred. OpenSSH is a lightweight alternative.

    Script flow:
      1. Install OpenSSH Server via Windows capability (or winget fallback)
      2. Start and enable the sshd service
      3. Configure firewall
      4. Set default shell to PowerShell (so AuditForge commands work)
      5. Verify connectivity

    Requires Windows 10 1809+ or Windows Server 2019+.

.PARAMETER SetPowerShellDefault
    Set PowerShell as the default SSH shell (recommended for AuditForge). Default: $true.

.NOTES
    Generated by AuditForge — https://github.com/louay-ouledali/Audit_Forge
    This is the FALLBACK when WinRM cannot be used.
#>

[CmdletBinding()]
param(
    [bool]$SetPowerShellDefault = $true
)

$ErrorActionPreference = "Stop"

# ── Must run as Administrator ───────────────────────────────────
if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error "This script must be run as Administrator."
    return
}

Write-Host ""
Write-Host "╔═══════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  AuditForge — Enable OpenSSH Server   ║" -ForegroundColor Cyan
Write-Host "╚═══════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── 1. Install OpenSSH Server ──────────────────────────────────
Write-Host "[1/5] Installing OpenSSH Server..." -ForegroundColor Yellow

$sshCapability = Get-WindowsCapability -Online | Where-Object { $_.Name -like 'OpenSSH.Server*' }

if ($sshCapability.State -eq 'Installed') {
    Write-Host "  ✓ OpenSSH Server already installed" -ForegroundColor Green
} elseif ($sshCapability.State -eq 'NotPresent') {
    try {
        Write-Host "  Installing via Add-WindowsCapability..." -ForegroundColor DarkGray
        Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 | Out-Null
        Write-Host "  ✓ OpenSSH Server installed" -ForegroundColor Green
    } catch {
        Write-Warning "Windows capability install failed. Trying winget fallback..."
        try {
            winget install Microsoft.OpenSSH.Server --accept-package-agreements --accept-source-agreements 2>&1 | Out-Null
            Write-Host "  ✓ OpenSSH Server installed via winget" -ForegroundColor Green
        } catch {
            Write-Error "Could not install OpenSSH Server. Install manually: Settings → Apps → Optional Features → OpenSSH Server"
            return
        }
    }
} else {
    Write-Host "  OpenSSH capability state: $($sshCapability.State) — attempting install..." -ForegroundColor DarkGray
    Add-WindowsCapability -Online -Name OpenSSH.Server~~~~0.0.1.0 -ErrorAction SilentlyContinue | Out-Null
}

# Also install OpenSSH Client (needed for ssh-keygen etc.)
$clientCap = Get-WindowsCapability -Online | Where-Object { $_.Name -like 'OpenSSH.Client*' }
if ($clientCap.State -ne 'Installed') {
    Add-WindowsCapability -Online -Name OpenSSH.Client~~~~0.0.1.0 -ErrorAction SilentlyContinue | Out-Null
    Write-Host "  ✓ OpenSSH Client also installed" -ForegroundColor Green
}

# ── 2. Start and enable sshd ───────────────────────────────────
Write-Host "[2/5] Starting SSH service..." -ForegroundColor Yellow

Set-Service -Name sshd -StartupType Automatic
Start-Service sshd
Write-Host "  ✓ sshd service running and set to auto-start" -ForegroundColor Green

# Also enable the ssh-agent
Set-Service -Name ssh-agent -StartupType Automatic -ErrorAction SilentlyContinue
Start-Service ssh-agent -ErrorAction SilentlyContinue

# ── 3. Firewall rule ───────────────────────────────────────────
Write-Host "[3/5] Configuring firewall..." -ForegroundColor Yellow

$fw = Get-NetFirewallRule -Name "AuditForge-OpenSSH" -ErrorAction SilentlyContinue
if (-not $fw) {
    # Check if the default OpenSSH rule exists
    $defaultFw = Get-NetFirewallRule -Name "OpenSSH-Server-In-TCP" -ErrorAction SilentlyContinue
    if ($defaultFw) {
        Enable-NetFirewallRule -Name "OpenSSH-Server-In-TCP"
        Write-Host "  ✓ Enabled default OpenSSH firewall rule" -ForegroundColor Green
    } else {
        New-NetFirewallRule -Name "AuditForge-OpenSSH" `
            -DisplayName "AuditForge OpenSSH" `
            -Direction Inbound -Protocol TCP -LocalPort 22 `
            -Action Allow -Profile Any | Out-Null
        Write-Host "  ✓ Firewall rule added: OpenSSH (port 22)" -ForegroundColor Green
    }
} else {
    Write-Host "  ✓ Firewall rule already exists" -ForegroundColor Green
}

# ── 4. Set PowerShell as default shell ──────────────────────────
Write-Host "[4/5] Configuring default shell..." -ForegroundColor Yellow

if ($SetPowerShellDefault) {
    $regPath = "HKLM:\SOFTWARE\OpenSSH"
    if (-not (Test-Path $regPath)) { New-Item -Path $regPath -Force | Out-Null }

    $psPath = (Get-Command powershell.exe).Source
    Set-ItemProperty -Path $regPath -Name DefaultShell -Value $psPath
    Write-Host "  ✓ Default SSH shell set to PowerShell" -ForegroundColor Green
    Write-Host "    ($psPath)" -ForegroundColor DarkGray
} else {
    Write-Host "  ⊘ Skipping — using cmd.exe as default shell" -ForegroundColor DarkGray
}

# ── 5. Verify ──────────────────────────────────────────────────
Write-Host "[5/5] Verifying SSH configuration..." -ForegroundColor Yellow
Write-Host ""

$svc = Get-Service sshd -ErrorAction SilentlyContinue
if ($svc.Status -eq 'Running') {
    Write-Host "  ✓ sshd is RUNNING" -ForegroundColor Green
} else {
    Write-Warning "sshd is not running: $($svc.Status)"
}

# Check port 22 is listening
$tcpCheck = Get-NetTCPConnection -LocalPort 22 -State Listen -ErrorAction SilentlyContinue
if ($tcpCheck) {
    Write-Host "  ✓ Port 22 is LISTENING" -ForegroundColor Green
} else {
    Write-Warning "Port 22 is NOT listening. Restart the sshd service."
}

# ── Summary ────────────────────────────────────────────────────
$vmIP = (Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object { $_.IPAddress -ne "127.0.0.1" -and $_.InterfaceAlias -notmatch "Loopback" } |
    Select-Object -First 1).IPAddress

Write-Host ""
Write-Host "═══════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  OpenSSH is ready for AuditForge!" -ForegroundColor Green
Write-Host "═══════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "  IP Address : $vmIP"
Write-Host "  SSH Port   : 22"
Write-Host ""
Write-Host "  In AuditForge, set:" -ForegroundColor Yellow
Write-Host "    IP Address       = $vmIP"
Write-Host "    Protocol         = SSH"
Write-Host "    Port             = 22"
Write-Host "    Username / Pass  = (your Windows admin credentials)"
Write-Host ""
Write-Host "  TIP: For key-based auth, add your public key to:" -ForegroundColor DarkGray
Write-Host "    C:\Users\<username>\.ssh\authorized_keys" -ForegroundColor DarkGray
Write-Host "    (or C:\ProgramData\ssh\administrators_authorized_keys for admins)" -ForegroundColor DarkGray
Write-Host ""
