<#
.SYNOPSIS
    Enables WinRM on a Windows target for AuditForge remote auditing.

.DESCRIPTION
    Run this script AS ADMINISTRATOR on the Windows machine you want to audit.
    It configures WinRM with both HTTP (5985) and HTTPS (5986) listeners,
    sets up the firewall rules, and validates the configuration.

    This script is safe to re-run — it skips steps that are already configured.

.PARAMETER SkipHTTPS
    Skip HTTPS listener creation (use HTTP only). Not recommended for production.

.PARAMETER AllowAllHosts
    Configure TrustedHosts to accept connections from any IP.
    Default: only allows the local subnet.

.NOTES
    Generated by AuditForge — https://github.com/louay-ouledali/Audit_Forge
    Compatible with: Windows 10, Windows 11, Windows Server 2016/2019/2022
#>

[CmdletBinding()]
param(
    [switch]$SkipHTTPS,
    [switch]$AllowAllHosts
)

$ErrorActionPreference = "Stop"

# ── Must run as Administrator ───────────────────────────────────
if (-not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    Write-Error "This script must be run as Administrator. Right-click PowerShell → Run as Administrator."
    return
}

Write-Host ""
Write-Host "╔═══════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║   AuditForge — Enable WinRM           ║" -ForegroundColor Cyan
Write-Host "╚═══════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

$stepCount = if ($SkipHTTPS) { 5 } else { 6 }
$step = 0

# ── 1. Enable WinRM service ────────────────────────────────────
$step++
Write-Host "[$step/$stepCount] Enabling WinRM service..." -ForegroundColor Yellow

try {
    Enable-PSRemoting -Force -SkipNetworkProfileCheck 2>&1 | Out-Null
    Write-Host "  ✓ PSRemoting enabled" -ForegroundColor Green
} catch {
    Write-Warning "Enable-PSRemoting failed: $_ — trying manual setup..."
    Set-Service -Name WinRM -StartupType Automatic
    Start-Service -Name WinRM
    Write-Host "  ✓ WinRM service started manually" -ForegroundColor Green
}

# ── 2. Configure WinRM settings ────────────────────────────────
$step++
Write-Host "[$step/$stepCount] Configuring WinRM authentication..." -ForegroundColor Yellow

winrm set winrm/config/service/auth '@{Basic="true"}' 2>$null | Out-Null
winrm set winrm/config/service/auth '@{Negotiate="true"}' 2>$null | Out-Null
winrm set winrm/config/service/auth '@{CredSSP="true"}' 2>$null | Out-Null

# Increase limits for large audit output
winrm set winrm/config '@{MaxTimeoutms="300000"}' 2>$null | Out-Null
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="2048"}' 2>$null | Out-Null
winrm set winrm/config/winrs '@{MaxConcurrentUsers="10"}' 2>$null | Out-Null

Write-Host "  ✓ Auth configured (Basic + Negotiate + CredSSP)" -ForegroundColor Green
Write-Host "  ✓ Limits raised (300s timeout, 2GB shell memory)" -ForegroundColor Green

# ── 3. HTTP listener ───────────────────────────────────────────
$step++
Write-Host "[$step/$stepCount] Ensuring HTTP listener (port 5985)..." -ForegroundColor Yellow

winrm quickconfig -quiet 2>&1 | Out-Null
Write-Host "  ✓ HTTP listener active on port 5985" -ForegroundColor Green

# ── 4. HTTPS listener ──────────────────────────────────────────
if (-not $SkipHTTPS) {
    $step++
    Write-Host "[$step/$stepCount] Configuring HTTPS listener (port 5986)..." -ForegroundColor Yellow

    $existingHttps = Get-ChildItem WSMan:\localhost\Listener -ErrorAction SilentlyContinue |
        Where-Object { $_.Keys -contains "Transport=HTTPS" }

    if ($existingHttps) {
        Write-Host "  ✓ HTTPS listener already exists" -ForegroundColor Green
    } else {
        $hostname = $env:COMPUTERNAME
        try {
            $cert = New-SelfSignedCertificate `
                -DnsName $hostname, "localhost" `
                -CertStoreLocation "cert:\LocalMachine\My" `
                -NotAfter (Get-Date).AddYears(5) `
                -KeyAlgorithm RSA -KeyLength 2048

            New-Item -Path WSMan:\localhost\Listener `
                -Transport HTTPS -Address * `
                -CertificateThumbPrint $cert.Thumbprint `
                -Force | Out-Null

            Write-Host "  ✓ HTTPS listener created (cert thumbprint: $($cert.Thumbprint.Substring(0,8))…)" -ForegroundColor Green
        } catch {
            Write-Warning "Could not create HTTPS listener: $_"
            Write-Host "  ℹ Falling back to HTTP-only. AuditForge will still work on port 5985." -ForegroundColor Yellow
        }
    }
}

# ── 5. Firewall rules ──────────────────────────────────────────
$step++
Write-Host "[$step/$stepCount] Configuring firewall rules..." -ForegroundColor Yellow

# HTTP rule
$fwHTTP = Get-NetFirewallRule -Name "AuditForge-WinRM-HTTP" -ErrorAction SilentlyContinue
if (-not $fwHTTP) {
    New-NetFirewallRule -Name "AuditForge-WinRM-HTTP" `
        -DisplayName "AuditForge WinRM HTTP" `
        -Direction Inbound -Protocol TCP -LocalPort 5985 `
        -Action Allow -Profile Any | Out-Null
    Write-Host "  ✓ Firewall rule added: WinRM HTTP (5985)" -ForegroundColor Green
} else {
    Write-Host "  ✓ Firewall rule exists: WinRM HTTP (5985)" -ForegroundColor Green
}

# HTTPS rule
if (-not $SkipHTTPS) {
    $fwHTTPS = Get-NetFirewallRule -Name "AuditForge-WinRM-HTTPS" -ErrorAction SilentlyContinue
    if (-not $fwHTTPS) {
        New-NetFirewallRule -Name "AuditForge-WinRM-HTTPS" `
            -DisplayName "AuditForge WinRM HTTPS" `
            -Direction Inbound -Protocol TCP -LocalPort 5986 `
            -Action Allow -Profile Any | Out-Null
        Write-Host "  ✓ Firewall rule added: WinRM HTTPS (5986)" -ForegroundColor Green
    } else {
        Write-Host "  ✓ Firewall rule exists: WinRM HTTPS (5986)" -ForegroundColor Green
    }
}

# TrustedHosts (if needed)
if ($AllowAllHosts) {
    Set-Item WSMan:\localhost\Client\TrustedHosts -Value "*" -Force
    Write-Host "  ✓ TrustedHosts set to *" -ForegroundColor Yellow
}

# ── 6. Verify ──────────────────────────────────────────────────
$step++
Write-Host "[$step/$stepCount] Verifying WinRM..." -ForegroundColor Yellow
Write-Host ""

$listeners = winrm enumerate winrm/config/listener 2>&1
$listeners | Select-String "Transport|Port" | ForEach-Object { Write-Host "  $_" }

try {
    $result = Invoke-Command -ComputerName localhost -ScriptBlock { $env:COMPUTERNAME } -ErrorAction Stop
    Write-Host ""
    Write-Host "  ✓ Local WinRM test PASSED (hostname: $result)" -ForegroundColor Green
} catch {
    Write-Warning "Local test failed — this may be a network profile issue. WinRM may still work for remote connections."
}

# ── Summary ────────────────────────────────────────────────────
$vmIP = (Get-NetIPAddress -AddressFamily IPv4 |
    Where-Object { $_.IPAddress -ne "127.0.0.1" -and $_.InterfaceAlias -notmatch "Loopback" } |
    Select-Object -First 1).IPAddress

Write-Host ""
Write-Host "═══════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  WinRM is ready for AuditForge!" -ForegroundColor Green
Write-Host "═══════════════════════════════════════" -ForegroundColor Cyan
Write-Host ""
Write-Host "  IP Address : $vmIP"
Write-Host "  HTTP Port  : 5985"
if (-not $SkipHTTPS) {
    Write-Host "  HTTPS Port : 5986"
}
Write-Host ""
Write-Host "  In AuditForge, set:" -ForegroundColor Yellow
Write-Host "    IP Address       = $vmIP"
Write-Host "    Protocol         = WinRM"
Write-Host "    Port             = $(if ($SkipHTTPS) {'5985'} else {'5986'})"
Write-Host "    Username / Pass  = (your target admin credentials)"
Write-Host ""
