"""initial schema

Revision ID: 823921b21a0f
Revises: 
Create Date: 2026-02-06 16:02:31.302124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823921b21a0f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    tables = sa.inspect(conn).get_table_names()

    if "app_settings" not in tables:
        op.create_table('app_settings',
        sa.Column('key', sa.Text(), nullable=False),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('key')
        )
    if "benchmarks" not in tables:
        op.create_table('benchmarks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('version', sa.String(), nullable=False),
        sa.Column('platform', sa.String(), nullable=False),
        sa.Column('platform_family', sa.String(), nullable=False),
        sa.Column('import_date', sa.DateTime(), nullable=True),
        sa.Column('pdf_filename', sa.String(), nullable=True),
        sa.Column('pdf_hash', sa.String(), nullable=True),
        sa.Column('total_rules', sa.Integer(), nullable=True),
        sa.Column('phase1_status', sa.String(), nullable=True),
        sa.Column('phase2_status', sa.String(), nullable=True),
        sa.Column('verification_status', sa.String(), nullable=True),
        sa.Column('is_ready', sa.Boolean(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('enrichment_stats', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if "clients" not in tables:
        op.create_table('clients',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('industry', sa.String(), nullable=True),
        sa.Column('contact_name', sa.String(), nullable=True),
        sa.Column('contact_email', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
    if "missions" not in tables:
        op.create_table('missions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('client_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=True),
        sa.Column('end_date', sa.Date(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if "rules" not in tables:
        op.create_table('rules',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('benchmark_id', sa.Integer(), nullable=False),
        sa.Column('section_number', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('rationale', sa.Text(), nullable=True),
        sa.Column('profile_applicability', sa.Text(), nullable=True),
        sa.Column('assessment_type', sa.String(), nullable=True),
        sa.Column('default_value', sa.Text(), nullable=True),
        sa.Column('references_json', sa.Text(), nullable=True),
        sa.Column('cis_controls', sa.Text(), nullable=True),
        sa.Column('audit_description_raw', sa.Text(), nullable=True),
        sa.Column('remediation_description_raw', sa.Text(), nullable=True),
        sa.Column('severity', sa.String(), nullable=True),
        sa.Column('enabled', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('benchmark_id', 'section_number')
        )
    if "scan_presets" not in tables:
        op.create_table('scan_presets',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('benchmark_id', sa.Integer(), nullable=True),
        sa.Column('selection_criteria', sa.Text(), nullable=False),
        sa.Column('rule_count', sa.Integer(), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
    if "rule_commands" not in tables:
        op.create_table('rule_commands',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('rule_id', sa.Integer(), nullable=False),
        sa.Column('audit_command', sa.Text(), nullable=True),
        sa.Column('expected_output_regex', sa.Text(), nullable=True),
        sa.Column('expected_output_description', sa.Text(), nullable=True),
        sa.Column('remediation_command', sa.Text(), nullable=True),
        sa.Column('remediation_description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('source', sa.String(), nullable=True),
        sa.Column('is_protected', sa.Boolean(), nullable=True),
        sa.Column('protection_reason', sa.Text(), nullable=True),
        sa.Column('protected_at', sa.DateTime(), nullable=True),
        sa.Column('verified_at', sa.DateTime(), nullable=True),
        sa.Column('verification_notes', sa.Text(), nullable=True),
        sa.Column('flagged_at', sa.DateTime(), nullable=True),
        sa.Column('flag_reason', sa.Text(), nullable=True),
        sa.Column('flag_error_output', sa.Text(), nullable=True),
        sa.Column('regeneration_count', sa.Integer(), nullable=True),
        sa.Column('last_regenerated_at', sa.DateTime(), nullable=True),
        sa.Column('previous_commands', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('rule_id')
        )
    if "rule_tags" not in tables:
        op.create_table('rule_tags',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('rule_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.String(), nullable=False),
        sa.Column('source', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('rule_id', 'tag_id')
        )
    if "targets" not in tables:
        op.create_table('targets',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('mission_id', sa.Integer(), nullable=False),
        sa.Column('hostname', sa.String(), nullable=True),
        sa.Column('ip_address', sa.String(), nullable=True),
        sa.Column('target_type', sa.String(), nullable=False),
        sa.Column('os_details', sa.String(), nullable=True),
        sa.Column('connection_method', sa.String(), nullable=True),
        sa.Column('ssh_username', sa.String(), nullable=True),
        sa.Column('ssh_key_path', sa.String(), nullable=True),
        sa.Column('ssh_password_encrypted', sa.Text(), nullable=True),
        sa.Column('port', sa.Integer(), nullable=True),
        sa.Column('db_connection_string_encrypted', sa.Text(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if "scans" not in tables:
        op.create_table('scans',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('target_id', sa.Integer(), nullable=False),
        sa.Column('benchmark_id', sa.Integer(), nullable=False),
        sa.Column('scan_mode', sa.String(), nullable=False),
        sa.Column('preset_id', sa.Integer(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('total_rules_checked', sa.Integer(), nullable=True),
        sa.Column('passed', sa.Integer(), nullable=True),
        sa.Column('failed', sa.Integer(), nullable=True),
        sa.Column('errors', sa.Integer(), nullable=True),
        sa.Column('not_applicable', sa.Integer(), nullable=True),
        sa.Column('manual_review', sa.Integer(), nullable=True),
        sa.Column('compliance_percentage', sa.Float(), nullable=True),
        sa.Column('script_generated_at', sa.DateTime(), nullable=True),
        sa.Column('results_imported_at', sa.DateTime(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], ),
        sa.ForeignKeyConstraint(['preset_id'], ['scan_presets.id'], ),
        sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if "verification_reports" not in tables:
        op.create_table('verification_reports',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('rule_command_id', sa.Integer(), nullable=False),
        sa.Column('level', sa.String(), nullable=False),
        sa.Column('result', sa.String(), nullable=False),
        sa.Column('message', sa.Text(), nullable=True),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('auto_fixable', sa.Boolean(), nullable=True),
        sa.Column('run_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['rule_command_id'], ['rule_commands.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    if "findings" not in tables:
        op.create_table('findings',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('scan_id', sa.Integer(), nullable=False),
        sa.Column('rule_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('actual_output', sa.Text(), nullable=True),
        sa.Column('expected_output', sa.Text(), nullable=True),
        sa.Column('severity', sa.String(), nullable=True),
        sa.Column('ai_advice', sa.Text(), nullable=True),
        sa.Column('ai_advice_generated_at', sa.DateTime(), nullable=True),
        sa.Column('auditor_notes', sa.Text(), nullable=True),
        sa.Column('auditor_override', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
        sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_table('verification_reports')
    op.drop_table('scans')
    op.drop_table('targets')
    op.drop_table('rule_tags')
    op.drop_table('rule_commands')
    op.drop_table('scan_presets')
    op.drop_table('rules')
    op.drop_table('missions')
    op.drop_table('clients')
    op.drop_table('benchmarks')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
