"""Pydantic schemas for pre-loaded benchmark packs (.auditforge.json).

This module defines the contract between the curation pipeline (scripts that
produce benchmark packs at development time) and the runtime loader that
imports them into the database at audit time.

Every field has a description so the JSON Schema generated by Pydantic
(``PreloadedBenchmarkPack.model_json_schema()``) is self-documenting.
"""

from __future__ import annotations

import hashlib
import json
import logging
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator

logger = logging.getLogger("auditforge.schemas.preloaded")

# Current schema version — bump when making breaking changes to the pack format
CURRENT_SCHEMA_VERSION = "2.0"


# ═══════════════════════════════════════════════════════════════════════════════
#  Sub-models
# ═══════════════════════════════════════════════════════════════════════════════


class PreloadedBenchmarkMeta(BaseModel):
    """Metadata block identifying the benchmark and its source PDF."""

    name: str = Field(
        ..., description="Full benchmark name, e.g. 'CIS Microsoft Windows 11 Enterprise Benchmark'"
    )
    version: str = Field(
        ..., description="Benchmark version string, e.g. '5.0.0'"
    )
    platform: str = Field(
        ..., description="Target platform, e.g. 'Windows 11 Enterprise', 'Ubuntu 24.04 LTS'"
    )
    platform_family: Literal["windows", "linux", "network", "database", "other", "container"] = Field(
        ..., description="Platform family for connector selection and template routing"
    )
    framework: str = Field(
        default="cis",
        description="Security framework: 'cis', 'stig', 'nist', 'iso', 'xccdf', 'custom'"
    )
    cis_pdf_hash: str | None = Field(
        None, description="SHA-256 hash of the source CIS PDF (prefixed with 'sha256:')"
    )
    total_rules: int = Field(
        ..., ge=1, description="Total number of rules in the pack"
    )
    release_date: str | None = Field(
        None, description="Benchmark release date (YYYY-MM-DD or approximate)"
    )


class NarrativeGroup(BaseModel):
    """A thematic group for clustering related findings in reports."""

    display_name: str = Field(
        ..., description="Human-readable group title shown in reports"
    )
    icon: str | None = Field(
        None, description="Icon identifier for the UI (e.g. 'shield-lock', 'eye', 'server')"
    )
    narrative_template: str = Field(
        ...,
        description=(
            "Template string for the group narrative. Available variables: "
            "{{failed_count}}, {{total_count}}, {{pass_rate}}, {{rule_list}}, "
            "{{worst_rule}}, {{worst_interpretation}}"
        ),
    )
    risk_summary_template: str | None = Field(
        None,
        description="Template for the risk impact summary within this group",
    )


class ChartDefaults(BaseModel):
    """Which chart types are most relevant for this benchmark."""

    primary: list[str] = Field(
        default=["donut", "hbar", "risk_heatmap"],
        description="Primary charts shown by default (max 3). Valid: donut, hbar, stacked_hbar, risk_heatmap, treemap, radar, waterfall, fp_gauge, mini_donut",
    )
    secondary: list[str] = Field(
        default=["treemap", "radar", "waterfall"],
        description="Secondary charts available on demand",
    )


class ReportProfile(BaseModel):
    """Report configuration baked into the pack — controls grouping, scoring, and chart selection."""

    narrative_groups: dict[str, NarrativeGroup] = Field(
        ..., description="Map of group_key → NarrativeGroup. Rule.narrative_group references these keys."
    )
    risk_weights: dict[str, int] = Field(
        default={"critical": 10, "high": 7, "medium": 4, "low": 1, "informational": 0},
        description="Severity label → numeric weight for weighted risk scoring",
    )
    chart_defaults: ChartDefaults = Field(
        default_factory=ChartDefaults,
        description="Chart type preferences for this benchmark",
    )

    @field_validator("narrative_groups")
    @classmethod
    def at_least_one_group(cls, v: dict[str, NarrativeGroup]) -> dict[str, NarrativeGroup]:
        if not v:
            raise ValueError("report_profile.narrative_groups must contain at least one group")
        return v


class RuleTag(BaseModel):
    """A functional category tag attached to a rule."""

    tag_id: str = Field(..., description="Tag identifier, e.g. 'password_policy', 'audit_logging'")
    source: str = Field(
        default="curated", description="Tag origin: 'curated', 'auto', 'imported'"
    )


class FPCondition(BaseModel):
    """A pre-defined false-positive detection condition for a specific rule.

    These are expert-authored conditions that fire deterministically at scan time
    without requiring LLM inference.
    """

    id: str = Field(
        ..., description="Unique identifier within the rule, e.g. 'domain_joined_default'"
    )
    condition_type: str = Field(
        ...,
        description=(
            "Type of condition check. Values: "
            "'output_pattern' (regex match on actual_output), "
            "'context_check' (requires system context like domain membership), "
            "'value_range' (actual value in a specific range), "
            "'service_absent' (service/feature not installed), "
            "'edition_mismatch' (wrong OS edition for this rule)"
        ),
    )
    check: str = Field(
        ...,
        description=(
            "The condition expression. For 'output_pattern': a regex. "
            "For 'context_check': a pseudo-expression like 'target.is_domain_joined == true'. "
            "For 'value_range': an expression like 'actual_value >= 20 AND actual_value <= 30'. "
            "For 'service_absent': the service/feature name. "
            "For 'edition_mismatch': the required edition."
        ),
    )
    verdict: Literal[
        "LIKELY_PASS", "NOT_APPLICABLE", "ACCEPTED_RISK", "NEEDS_REVIEW"
    ] = Field(
        ..., description="Suggested finding status if this condition matches"
    )
    confidence: int = Field(
        ..., ge=0, le=100, description="Confidence score (0-100) that this is a true false positive"
    )
    explanation: str = Field(
        ..., description="Human-readable explanation shown in the report when this condition fires"
    )


class PreloadedRule(BaseModel):
    """A single enriched rule within a pre-loaded benchmark pack.

    Contains everything needed to scan, evaluate, detect false positives,
    and produce intelligent reports — without any LLM calls at runtime.
    """

    # ── Identity (from Phase 1) ──────────────────────────────────────────
    section_number: str = Field(..., description="CIS section number, e.g. '1.1.1', '18.10.3.2'")
    title: str = Field(..., description="Rule title from the CIS benchmark")
    description: str | None = Field(None, description="Full rule description from the CIS PDF")
    rationale: str | None = Field(None, description="Why this rule matters (from CIS PDF)")
    profile_applicability: list[str] | None = Field(
        None, description="Applicable CIS profiles, e.g. ['Level 1 (L1)', 'Level 2 (L2)']"
    )
    assessment_type: str | None = Field(
        None, description="'automated' or 'manual'"
    )
    default_value: str | None = Field(
        None, description="Documented OS/platform default value for this setting"
    )
    severity: Literal["critical", "high", "medium", "low", "informational"] = Field(
        default="medium", description="Rule severity level"
    )
    cis_controls: str | None = Field(
        None, description="CIS Controls mapping, e.g. 'v8: 5.2'"
    )
    enabled: bool = Field(default=True, description="Whether this rule is active by default")
    tags: list[RuleTag] = Field(default_factory=list, description="Functional category tags")

    # ── Multi-framework fields (schema v2.0) ─────────────────────────────
    framework_ref: str | None = Field(
        None,
        description="Original reference ID in the source framework (e.g. STIG 'V-253283', NIST 'AC-2(1)', ISO 'A.5.1')"
    )

    # ── Audit command (from Phase 2, curated) ────────────────────────────
    audit_command: str | None = Field(
        None, description="The audit command (PowerShell / Bash / SQL) to check this rule"
    )
    expected_output_expression: str | None = Field(
        None,
        description=(
            "Comparison expression for the expected output. "
            "Formats: '>=24', '<=365', '==1', '!=0', 'not_empty', "
            "'contains:keyword', 'not_contains:keyword', 'regex:pattern'"
        ),
    )
    expected_output_description: str | None = Field(
        None, description="Human-readable description of what the expected output means"
    )
    remediation_command: str | None = Field(
        None, description="Command to fix this rule if it fails (PowerShell / Bash / SQL)"
    )
    remediation_description: str | None = Field(
        None, description="Human-readable remediation instructions"
    )

    # ── Baked intelligence ────────────────────────────────────────────────
    empty_output_interpretation: str | None = Field(
        None,
        description=(
            "What it means when the audit command returns empty output. "
            "E.g. 'Registry key does not exist — Windows applies the default value of 42 days.'"
        ),
    )
    output_value_map: dict[str, str] | None = Field(
        None,
        description=(
            "Map of commonly seen output values to human-readable interpretations. "
            "E.g. {'0': 'Feature is disabled', 'NOT_CONFIGURED': 'Using OS default'}"
        ),
    )
    fp_conditions: list[FPCondition] = Field(
        default_factory=list,
        description="Pre-defined false positive conditions (expert-authored, deterministic)",
    )

    # ── Remediation metadata ─────────────────────────────────────────────
    remediation_gpo_path: str | None = Field(
        None,
        description="Group Policy path for Windows rules, e.g. 'Computer Configuration\\...\\Enforce password history'",
    )
    remediation_risk: Literal["low", "medium", "high"] | None = Field(
        None, description="Risk level of applying the remediation (low = safe, high = may break things)"
    )
    safe_to_automate: bool = Field(
        default=False, description="Whether the remediation can be safely auto-applied without human review"
    )
    requires_restart: bool = Field(
        default=False, description="Whether the remediation requires a system reboot to take effect"
    )

    # ── Semantic metadata ────────────────────────────────────────────────
    narrative_group: str | None = Field(
        None,
        description="Key into report_profile.narrative_groups — determines report grouping",
    )
    security_themes: list[str] = Field(
        default_factory=list,
        description="Security theme tags, e.g. ['authentication', 'credential-protection']",
    )
    attack_chain_tags: list[str] = Field(
        default_factory=list,
        description="Attack chain identifiers, e.g. ['credential-bruteforce', 'lateral-movement']",
    )
    mitre_attack: list[str] = Field(
        default_factory=list,
        description="MITRE ATT&CK technique IDs, e.g. ['T1110.001', 'T1078']",
    )
    risk_weight: int = Field(
        default=5, ge=1, le=10,
        description="Risk weight (1-10) for weighted risk scoring. 10 = most critical.",
    )
    related_rules: list[str] = Field(
        default_factory=list,
        description="Section numbers of related rules (informational cross-reference)",
    )
    group_with: list[str] = Field(
        default_factory=list,
        description="Section numbers of rules that should be grouped together in reports",
    )


# ═══════════════════════════════════════════════════════════════════════════════
#  Top-level pack schema
# ═══════════════════════════════════════════════════════════════════════════════


class PreloadedBenchmarkPack(BaseModel):
    """Top-level schema for a pre-loaded benchmark pack (.auditforge.json).

    This is the single source of truth that ships with AuditForge for each
    supported benchmark. It contains everything needed to scan, evaluate,
    detect false positives, and produce intelligent reports — without
    requiring any LLM at audit time.
    """

    schema_version: str = Field(
        default=CURRENT_SCHEMA_VERSION,
        description="Pack schema version for forward compatibility",
    )
    benchmark: PreloadedBenchmarkMeta = Field(
        ..., description="Benchmark identification and metadata"
    )
    report_profile: ReportProfile = Field(
        ..., description="Report configuration: narrative groups, risk weights, chart preferences"
    )
    rules: list[PreloadedRule] = Field(
        ..., min_length=1, description="Array of enriched rules"
    )

    # ── Cross-field validators ───────────────────────────────────────────

    @model_validator(mode="after")
    def validate_rule_count_matches(self) -> PreloadedBenchmarkPack:
        """Ensure benchmark.total_rules matches actual rules count."""
        actual = len(self.rules)
        declared = self.benchmark.total_rules
        if actual != declared:
            raise ValueError(
                f"benchmark.total_rules is {declared} but rules array has {actual} entries"
            )
        return self

    @model_validator(mode="after")
    def validate_narrative_group_references(self) -> PreloadedBenchmarkPack:
        """Ensure every rule's narrative_group references a defined group."""
        defined_groups = set(self.report_profile.narrative_groups.keys())
        orphans: list[str] = []
        for rule in self.rules:
            if rule.narrative_group and rule.narrative_group not in defined_groups:
                orphans.append(f"{rule.section_number} -> '{rule.narrative_group}'")
        if orphans:
            raise ValueError(
                f"Rules reference undefined narrative_groups: {', '.join(orphans[:10])}"
                + (f" (+{len(orphans) - 10} more)" if len(orphans) > 10 else "")
            )
        return self

    @model_validator(mode="after")
    def validate_no_duplicate_sections(self) -> PreloadedBenchmarkPack:
        """Ensure no duplicate section_number values in the rules array."""
        seen: dict[str, int] = {}
        dupes: list[str] = []
        for i, rule in enumerate(self.rules):
            if rule.section_number in seen:
                dupes.append(rule.section_number)
            seen[rule.section_number] = i
        if dupes:
            raise ValueError(
                f"Duplicate section_number values: {', '.join(dupes[:10])}"
            )
        return self

    @model_validator(mode="after")
    def validate_group_with_references(self) -> PreloadedBenchmarkPack:
        """Ensure group_with references point to rules that exist in the pack."""
        all_sections = {r.section_number for r in self.rules}
        bad_refs: list[str] = []
        for rule in self.rules:
            for ref in rule.group_with:
                if ref not in all_sections:
                    bad_refs.append(f"{rule.section_number}.group_with -> '{ref}'")
        if bad_refs:
            raise ValueError(
                f"group_with references non-existent rules: {', '.join(bad_refs[:10])}"
                + (f" (+{len(bad_refs) - 10} more)" if len(bad_refs) > 10 else "")
            )
        return self


# ═══════════════════════════════════════════════════════════════════════════════
#  Pack validation & loading utilities
# ═══════════════════════════════════════════════════════════════════════════════


class PackValidationResult(BaseModel):
    """Summary of a pack validation run."""

    valid: bool = Field(..., description="Whether the pack passed all checks")
    errors: list[str] = Field(default_factory=list, description="Validation errors")
    warnings: list[str] = Field(default_factory=list, description="Non-fatal warnings")
    stats: dict[str, Any] = Field(default_factory=dict, description="Completeness statistics")


def validate_pack(path: str | Path) -> tuple[PreloadedBenchmarkPack | None, PackValidationResult]:
    """Load and validate a .auditforge.json pack file.

    Parameters
    ----------
    path : str | Path
        Path to the .auditforge.json file.

    Returns
    -------
    tuple[PreloadedBenchmarkPack | None, PackValidationResult]
        The parsed pack (or None if validation failed) and a detailed result.
    """
    path = Path(path)
    errors: list[str] = []
    warnings: list[str] = []

    # ── File-level checks ────────────────────────────────────────────────
    if not path.exists():
        return None, PackValidationResult(valid=False, errors=[f"File not found: {path}"])
    if not path.suffix == ".json" and not path.name.endswith(".auditforge.json"):
        warnings.append(f"Unexpected file extension: {path.suffix} (expected .auditforge.json)")

    try:
        raw = path.read_text(encoding="utf-8")
    except Exception as exc:
        return None, PackValidationResult(valid=False, errors=[f"Cannot read file: {exc}"])

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        return None, PackValidationResult(valid=False, errors=[f"Invalid JSON: {exc}"])

    # ── Schema validation ────────────────────────────────────────────────
    try:
        pack = PreloadedBenchmarkPack.model_validate(data)
    except Exception as exc:
        return None, PackValidationResult(valid=False, errors=[str(exc)])

    # ── Completeness checks (warnings, not errors) ───────────────────────
    total = len(pack.rules)
    with_commands = sum(1 for r in pack.rules if r.audit_command)
    with_expression = sum(1 for r in pack.rules if r.expected_output_expression)
    with_empty_interp = sum(1 for r in pack.rules if r.empty_output_interpretation)
    with_fp_conditions = sum(1 for r in pack.rules if r.fp_conditions)
    with_narrative = sum(1 for r in pack.rules if r.narrative_group)
    with_mitre = sum(1 for r in pack.rules if r.mitre_attack)
    with_remediation = sum(1 for r in pack.rules if r.remediation_command)

    pct = lambda n: round(n / total * 100) if total else 0  # noqa: E731

    if with_commands < total:
        warnings.append(f"{total - with_commands} rules missing audit_command ({pct(with_commands)}% complete)")
    if with_expression < total:
        warnings.append(f"{total - with_expression} rules missing expected_output_expression ({pct(with_expression)}% complete)")
    if with_empty_interp < total * 0.9:
        warnings.append(f"Only {pct(with_empty_interp)}% of rules have empty_output_interpretation (target: >=90%)")
    if with_fp_conditions < total * 0.5:
        warnings.append(f"Only {pct(with_fp_conditions)}% of rules have fp_conditions (target: >=80%)")
    if with_narrative < total:
        warnings.append(f"{total - with_narrative} rules missing narrative_group ({pct(with_narrative)}% complete)")
    if with_mitre < total * 0.7:
        warnings.append(f"Only {pct(with_mitre)}% of rules have MITRE ATT&CK mapping (target: >=70%)")

    # ── Related/group_with symmetry check ────────────────────────────────
    section_set = {r.section_number for r in pack.rules}
    for rule in pack.rules:
        for ref in rule.related_rules:
            if ref not in section_set:
                warnings.append(
                    f"Rule {rule.section_number}: related_rules references '{ref}' which is not in the pack"
                )

    stats = {
        "total_rules": total,
        "with_audit_command": with_commands,
        "with_expression": with_expression,
        "with_empty_interpretation": with_empty_interp,
        "with_fp_conditions": with_fp_conditions,
        "with_narrative_group": with_narrative,
        "with_mitre_attack": with_mitre,
        "with_remediation_command": with_remediation,
        "narrative_groups_defined": len(pack.report_profile.narrative_groups),
        "completeness_pct": {
            "commands": pct(with_commands),
            "expressions": pct(with_expression),
            "empty_interpretation": pct(with_empty_interp),
            "fp_conditions": pct(with_fp_conditions),
            "narrative_groups": pct(with_narrative),
            "mitre_attack": pct(with_mitre),
            "remediation_commands": pct(with_remediation),
        },
    }

    return pack, PackValidationResult(
        valid=True,
        errors=errors,
        warnings=warnings,
        stats=stats,
    )


def compute_pack_hash(path: str | Path) -> str:
    """Compute SHA-256 hash of a pack file for change detection."""
    sha256 = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            sha256.update(chunk)
    return sha256.hexdigest()
